---
- name: Debian - Install nginx-extras
  become: true
  package:
    name: nginx-extras
    state: present
    force: yes
    update_cache: yes

- name: Debian - Create sites-available & sites-enabled directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/nginx/sites-available/
    - /etc/nginx/sites-enabled/

- name: Debian - Copy nginx.conf
  become: true
  copy:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Debian - Copy {{ domain }} sites-available configuration
  become: true
  template:
    src: etc/nginx/sites-available/default.j2
    dest: /etc/nginx/sites-available/{{ domain }}
    owner: root
    group: root
    mode: 0644
    backup: true

- name: Debian - Link sites-enabled configuration
  become: true
  file:
    state: link
    src: /etc/nginx/sites-available/{{ domain }}
    dest: /etc/nginx/sites-enabled/{{ domain }}
    force: yes

- name: Debian - Unlink default configuration
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
