---
- name: FreeBSD - Install nginx
  become: true
  pkgng:
    name: nginx
    state: present

- name: FreeBSD - Add nginx_enable="YES" to /etc/rc.conf
  become: true
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^nginx_enable="YES"'
    line: 'nginx_enable="YES"'
    state: present

- name: FreeBSD - Start nginx
  service:
    name: nginx
    state: restarted

- name: FreeBSD - Create sites-available & sites-enabled directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: wheel
    mode: 0755
  with_items:
    - /usr/local/etc/nginx/sites-available/
    - /usr/local/etc/nginx/sites-enabled/

- name: FreeBSD - Copy nginx.conf
  become: true
  copy:
    src: etc/nginx/nginx.conf.freebsd
    dest: /usr/local/etc/nginx/nginx.conf
    owner: root
    group: wheel
    mode: 0644
    backup: yes

- name: FreeBSD - Copy {{ domain }} sites-available configuration
  become: true
  template:
    src: etc/nginx/sites-available/default.j2
    dest: /usr/local/etc/nginx/sites-available/{{ domain }}
    owner: root
    group: wheel
    mode: 0644
    backup: true

- name: FreeBSD - Link sites-enabled configuration
  become: true
  file:
    state: link
    src: /usr/local/etc/nginx/sites-available/{{ domain }}
    dest: /usr/local/etc/nginx/sites-enabled/{{ domain }}
    force: yes

- name: FreeBSD - Unlink default configuration
  become: true
  file:
    path: /usr/local/etc/nginx/sites-enabled/default
    state: absent
