---
- include: debian.yml
  when: ansible_distribution == 'Debian'

- include: fedora.yml
  when: ansible_distribution == 'Fedora'

- include: freebsd.yml
  when: ansible_distribution == 'FreeBSD'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Restart nginx
  become: true
  service:
    name: nginx
    state: restarted
