---
- name: Download Grav
  become: true
  unarchive:
    src: https://github.com/getgrav/grav/releases/download/1.2.4/grav-admin-v1.2.4.zip
    dest: /tmp
    remote_src: True

- name: Delete {{ domain }} webroot
  become: true
  file:
    path: /var/www/{{ domain }}
    state: absent

- name: Create {{ domain }} webroot
  become: true
  file: 
    path: /var/www/{{ domain }}
    state: directory

- name: Move Grav to webroot
  become: true
  shell: mv /tmp/grav-admin/ /var/www/{{ domain }}/grav-admin

- name: Set permissions on webroot (Fedora)
  become: true
  shell: |
    chown -R apache:apache /var/www/{{ domain }}/grav-admin
    find /var/www/{{ domain }}/grav-admin -type f | xargs chmod 664
    find /var/www/{{ domain }}/grav-admin/bin -type f | xargs chmod 775
    find /var/www/{{ domain }}/grav-admin -type d | xargs chmod 775
    find /var/www/{{ domain }}/grav-admin -type d | xargs chmod +s
    umask 0002
   when: ansible_distribution == "Fedora"

- name: Set permissions on webroot (Ubuntu)
  become: true
  shell: |
    chown -R www-data:www-data /var/www/{{ domain }}/grav-admin
    find /var/www/{{ domain }}/grav-admin -type f | xargs chmod 664
    find /var/www/{{ domain }}/grav-admin/bin -type f | xargs chmod 775
    find /var/www/{{ domain }}/grav-admin -type d | xargs chmod 775
    find /var/www/{{ domain }}/grav-admin -type d | xargs chmod +s
    umask 0002
   when: ansible_distribution == "Ubuntu"