---
- name: Download Grav
  become: true
  unarchive:
    src: https://github.com/getgrav/grav/releases/download/1.2.4/grav-admin-v1.2.4.zip
    dest: /tmp
    remote_src: True

- name: Delete default webroot
  become: true
  file:
    path: /var/www/html
    state: absent

- name: Move Grav to webroot
  become: true
  shell: mv /tmp/grav-admin/ /var/www/html

- name: Download permissions script
  become: true
  get_url:
    url: https://raw.githubusercontent.com/andywimmer/grav-nginx-configs/master/perms.sh
    dest: /var/www/html

- name: chmod +x permissions script
  become: true
  file:
    path: /var/www/html/perms.sh
    mode: "a+x"

- name: Run permissions script
  become: true
  shell: cd /var/www/html/ && ./perms.sh

- name: Install Grav Nginx site
  become: true
  get_url:
    url: https://raw.githubusercontent.com/andywimmer/grav-nginx-configs/master/sites-available/grav
    dest: /etc/nginx/sites-available/default

- name: Configure Grav Nginx site with FQDN
  become: true
  replace:
    path: /etc/nginx/sites-available/default
    regexp: '(\s+)example\.com(\s+.*)?$'
    replace: '\1{{ domain }}\2'

- name: Configure Grav Nginx site with www.FQDN
  become: true
  replace:
    path: /etc/nginx/sites-available/default
    regexp: '(\s+)www\.example\.com\;(\s+.*)?$'
    replace: '\1www.{{ domain }};\2'

- name: Install Grav nginx.conf
  become: true
  get_url:
    url: https://raw.githubusercontent.com/andywimmer/grav-nginx-configs/master/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
