---
- name: Download Grav
  become: true
  unarchive:
    src: https://github.com/getgrav/grav/releases/download/1.2.4/grav-admin-v1.2.4.zip
    dest: /tmp
    remote_src: True

- name: Delete webroot
  become: true
  file:
    path: /var/www/html
    state: absent

- name: Install Grav to webroot
  become: true
  shell: mv /tmp/grav-admin/ /var/www/html

- include: debian.yml
  when: ansible_distribution == 'Debian'

- include: fedora.yml
  when: ansible_distribution == 'Fedora'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
