---
- name: Ubuntu - Install Grav to webroot
  become: true
  shell: mv /tmp/grav-admin/* /var/www/html/.

- name: Ubuntu - Set permissions on webroot
  become: true
  shell: |
    chown -R www-data:www-data /var/www/html
    find /var/www/html -type f | xargs chmod 664
    find /var/www/html/bin -type f | xargs chmod 775
    find /var/www/html -type d | xargs chmod 775
    find /var/www/html -type d | xargs chmod +s
    umask 0002
