---
- name: Install base packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - epel-release
  - gcc
  - make
  - ufw
  - unzip
  - yum-utils

- include: nginx.yml

- include: php.yml

- include: grav.yml
