---
- name: PHP - Add repository
  become: true
  yum:
    name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    state: present

- name: PHP - Install
  become: true
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - libyaml-devel
  - php71w-cli
  - php71w-common
  - php71w-curl
  - php71w-devel
  - php71w-fpm
  - php71w-gd
  - php71w-mbstring
  - php71w-mcrypt
  - php71w-opcache
  - php71w-pear
  - php71w-pecl-apcu
  - php71w-process
  - php71w-xml
  - php71w-xmlrpc
  - php71w-zip

- name: PHP - Install YAML parser
  become: true
  shell: pecl install yaml-2.0.0

- name: PHP - Set php.ini cgi.fix_pathinfo=0
  become: true
  replace:
    path: /etc/php.ini
    regexp: '(\s+)\;cgi\.fix_pathinfo\=1(\s+.*)?$'
    replace: '\1cgi.fix_pathinfo=0\2'

- name: PHP - Set php.ini opcache.memory_consumption=128
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: '^opcache.memory_consumption=128'
    line: 'opcache.memory_consumption=128'

- name: PHP - Set php.ini opcache.interred_strings_buffer=16
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: '^opcache.interned_strings_buffer=8'
    line: 'opcache.interned_strings_buffer=16'

- name: PHP - Set php.ini opcache.max_accelerated_files=10000
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: '^opcache.max_accelerated_files=10000'
    line: 'opcache.max_accelerated_files=10000'

- name: PHP - Set php.ini opcache.revalidate_freq=60
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: '^opcache.revalidate_freq=2'
    line: 'opcache.revalidate_freq=60'

- name: PHP - Set php.ini opcache.fast_shutdown=1
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: '^opcache.fast_shutdown=0'
    line: 'opcache.fast_shutdown=1'

- name: PHP - Add apc.shm_size=64M to php.ini
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: "^apc.shm_size=64M"
    line: "apc.shm_size=64M"
    state: present

- name: PHP - Set www.conf user
  become: true
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: '(\s+)user\s=\sapache(\s+.*)?$'
    replace: '\1user = nginx\2'

- name: PHP - Set www.conf group
  become: true
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: '(\s+)group\s=\sapache(\s+.*)?$'
    replace: '\1group = nginx\2'

- name: PHP - Enable service
  become: true
  shell: systemctl enable php-fpm

- name: PHP - Restart
  become: true
  service:
    name: php-fpm
    state: restarted
