---
- hosts: prod
  tasks:
    - group_by: key=os_{{ ansible_distribution }}

- hosts: os_Amazon
  gather_facts: False
  roles:
    - common
    - amazon

- hosts: os_CentOS
  gather_facts: False
  roles:
    - common
    - centos
    - ufw

- hosts: os_Debian
  gather_facts: False
  roles:
    - common
    - debian
    - ufw

- hosts: os_Fedora
  gather_facts: False
  roles:
    - common
    - fedora
    - ufw

- hosts: os_Ubuntu
  gather_facts: False
  roles:
    - common
    - ubuntu
    - ufw
