---
- hosts: prod
  vars_prompt:
    - name: "domain"
      prompt: "enter your FQDN such as 'example.com' or 'demo1.something.xyz'. Do not include the 'www'"
      private: no
  roles:
   - common
   - ufw
   - nginx
   - php
   - grav
