---
- name: PHP - Install PHP
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
  - php-cli
  - php-common
  - php-curl
  - php-fpm
  - php-gd
  - php-mbstring
  - php-mcrypt
  - php-opcache
  - php-xml
  - php-xmlrpc
  - php-zip
  - php-apcu
  - php-pear

- name: PHP - Set PHP cgi.fix_pathinfo to 0
  become: true
  replace:
    path: /etc/php.ini
    regexp: '(\s+)\;cgi\.fix_pathinfo\=1(\s+.*)?$'
    replace: '\1cgi.fix_pathinfo=0\2'

- name: PHP - Set PHP OpCache Memory Consumption to 128MB
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: '^opcache.memory_consumption=128'
    line: 'opcache.memory_consumption=128'

- name: PHP - Set PHP OpCache Interred Strings Buffer to 16MB
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: '^opcache.interned_strings_buffer=8'
    line: 'opcache.interned_strings_buffer=16'

- name: PHP - Set PHP OpCache Max Accelerated Files to 10,000
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: '^opcache.max_accelerated_files=10000'
    line: 'opcache.max_accelerated_files=10000'

- name: PHP - Set PHP OpCache Revalidate Frequency to 60s
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: '^opcache.revalidate_freq=2'
    line: 'opcache.revalidate_freq=60'

- name: PHP - Set PHP OpCache Fast Shutdown On
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: '^opcache.fast_shutdown=0'
    line: 'opcache.fast_shutdown=1'

- name: PHP - Add "extension=yaml.so" to php.ini
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: "^extension=yaml.so"
    line: "extension=yaml.so"
    state: present

- name: PHP - Add "apc.shm_size=64M" to php.ini
  become: true
  lineinfile:
    dest: /etc/php.ini
    regexp: "^apc.shm_size=64M"
    line: "apc.shm_size=64M"
    state: present

- name: PHP - Set PHP www.conf socket
  become: true
  replace:
    path: /etc/php-fpm.d/www.conf
    regexp: '(\s+)\/run\/php\-fpm\/www\.sock(\s+.*)?$'
    replace: '\1/var/run/php-fpm.sock\2'

- name: PHP - Restart PHP
  service:
    name: php-fpm
    state: restarted
