---
- name: Update and upgrade packages
  become: true
  apt:
    upgrade: dist
    update_cache: yes

- name: Install base packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - apt-transport-https
  - make
  - software-properties-common
  - ufw
  - unzip

- include: nginx.yml

- include: php.yml

- include: grav.yml