---
- name: NGINX - Install repository
  become: true
  package:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    state: present

- name: NGINX - Install nginx
  become: true
  package:
    name: nginx
    state: present

- name: NGINX - Create sites-available & sites-enabled directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/nginx/sites-available/
    - /etc/nginx/sites-enabled/
