---
# - name: CentOS - Update and upgrade packages
#   become: true
#   yum:
#     name: '*'
#     state: latest

- name: CentOS - Install base packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - epel-release
  - make
  - ufw
  - unzip
  - yum-utils
