---
- name: Debian - Update and upgrade packages
  become: true
  apt:
    upgrade: dist
    update_cache: yes

- name: Debian - Install base packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - apt-transport-https
  - make
  - software-properties-common
  - ufw
  - unzip
