---
- name: FreeBSD - Add php_fpm_enable="YES" to /etc/rc.conf
  become: true
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^php_fpm_enable="YES"'
    line: 'php_fpm_enable="YES"'
    state: present

- name: FreeBSD - Set PHP cgi.fix_pathinfo to 0
  become: true
  replace:
    path: /usr/local/etc/php.ini-production
    regexp: '(\s+)\;cgi\.fix_pathinfo\=1(\s+.*)?$'
    replace: '\1cgi.fix_pathinfo=0\2'

- name: FreeBSD - Set PHP OpCache Memory Consumption to 128MB
  become: true
  lineinfile:
    dest: /usr/local/etc/php.ini-production
    regexp: '^opcache.memory_consumption=128'
    line: 'opcache.memory_consumption=128'

- name: FreeBSD - Set PHP OpCache Interred Strings Buffer to 16MB
  become: true
  lineinfile:
    dest: /usr/local/etc/php.ini-production
    regexp: '^opcache.interned_strings_buffer=8'
    line: 'opcache.interned_strings_buffer=16'

- name: FreeBSD - Set PHP OpCache Max Accelerated Files to 10,000
  become: true
  lineinfile:
    dest: /usr/local/etc/php.ini-production
    regexp: '^opcache.max_accelerated_files=10000'
    line: 'opcache.max_accelerated_files=10000'

- name: FreeBSD - Set PHP OpCache Revalidate Frequency to 60s
  become: true
  lineinfile:
    dest: /usr/local/etc/php.ini-production
    regexp: '^opcache.revalidate_freq=2'
    line: 'opcache.revalidate_freq=60'

- name: FreeBSD - Set PHP OpCache Fast Shutdown On
  become: true
  lineinfile:
    dest: /usr/local/etc/php.ini-production
    regexp: '^opcache.fast_shutdown=0'
    line: 'opcache.fast_shutdown=1'

- name: FreeBSD - Add "extension=yaml.so" to php.ini
  become: true
  lineinfile:
    dest: /usr/local/etc/php.ini-production
    regexp: "^extension=yaml.so"
    line: "extension=yaml.so"
    state: present

- name: FreeBSD - Add "apc.shm_size=64M" to php.ini
  become: true
  lineinfile:
    dest: /usr/local/etc/php.ini-production
    regexp: "^apc.shm_size=64M"
    line: "apc.shm_size=64M"
    state: present

- name: FreeBSD - Start PHP
  service:
    name: php-fpm
    state: restarted
